exclude: ^(venv/|.venv/env/|.env/|version.txt|__pycache__/|.*\.pyc|.mypy_cache/)
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
        - id: isort
          args: ["--line-length=97", "--profile=black"]

-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
        - id: black
          args: ["--line-length=97", "--target-version=py312"]

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=97", "--ignore=E402"]

#- repo: https://github.com/pre-commit/mirrors-mypy
#  rev: v1.8.0
#  hooks:
#  - id: mypy
#    args: ["--ignore-missing-imports"]
#
#-   repo: https://github.com/PyCQA/pylint
#    rev: v3.1.0
#    hooks:
#    -   id: pylint
#        args: ["--disable=C0114,C0115,C0116,W1203"]
